version: '3.9'

services:
  node-app:
    image: node:22-alpine
    container_name: node-app
    user: "${UID:-1000}:${GID:-1000}"
    networks:
      - app-network
    ports:
      - "1337:1337"
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: "tail -f /dev/null"

  postgres-db:
    image: postgres:17
    container_name: postgres-db
    networks:
      - app-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
